# Generated by Django 5.1.6 on 2025-02-15 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permit',
            name='permit_type',
            field=models.CharField(choices=[('Restricted', 'Restricted'), ('Temporary', 'Temporary'), ('Permanent', 'Permanent')], max_length=20),
        ),
        migrations.AlterField(
            model_name='permit',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Invalid', 'Invalid')], default='Pending', max_length=20),
        ),
    ]
